[project]
name = "freewili-updater"
version = "0.1.0"
description = "Free-Wili firmware updater"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "freewili==0.0.25.post7.dev0",
    "pyside6>=6.9.0",
    "result>=0.17.0",
]
