name: Build

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-24.04, macos-15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - run: uv sync --dev

      - name: Build executable
        shell: bash
        run: |
          pyside6-uic ./src/ui/main.ui -o ./src/ui/main.py --from-imports .
          pyside6-rcc ./src/ui/main.qrc -o ./src/ui/main_rc.py
          pyinstaller main.spec
          
      - name: Rename executable for platform
        shell: bash
        run: |
          # Rename executable to include OS type
          if [[ "${{ matrix.os }}" == windows-* ]]; then
            cp dist/freewili-updater.exe dist/freewili-updater-${{ matrix.os }}-${{ github.ref_name }}.exe
            rm dist/freewili-updater.exe
          else
            cp dist/freewili-updater dist/freewili-updater-${{ matrix.os }}-${{ github.ref_name }}
            chmod +x dist/freewili-updater-${{ matrix.os }}-${{ github.ref_name }}
            rm dist/freewili-updater
          fi

      - name: Get short commit hash
        id: get_hash
        shell: bash
        run: |
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV |
          echo "Git hash is $GIT_HASH"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: freewili-updater-${{ matrix.os }}-${{ github.ref_name }}
          path: dist/

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts as zip files
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: false
      
      - name: Create zip files from artifacts
        run: |
          mkdir -p release-zips
          for artifact_dir in artifacts/*/; do
            artifact_name=$(basename "$artifact_dir")
            echo "Creating zip for: $artifact_name"
            cd "$artifact_dir"
            zip -r "../../release-zips/${artifact_name}.zip" *
            cd ../..
          done
          
          echo "Release zip files:"
          ls -la release-zips/
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: release-zips/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
